import { Button, VerticalBox , AboutSlint } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 800px;
    height: 480px;
    in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox { 
        Text {
            text: "Counter: \{root.counter}";
            font-size: 50px;
            horizontal-alignment: center;
        }
        Button {
            text: "Increase value";
            clicked => { 
                root.request-increase-value();
            }
        }
        AboutSlint {
        }
     }
}